<?php $__env->startSection('title', 'Contact Us — Lone Star Solutions Texas'); ?>

<?php $__env->startSection('content'); ?>
<div style="background:var(--navy);padding:56px 24px"><div style="max-width:1280px;margin:0 auto"><div class="accent-line left"></div><h1 style="font-family:'Oswald',sans-serif;font-weight:700;text-transform:uppercase;letter-spacing:.04em;color:#fff;font-size:clamp(28px,4vw,48px);margin-bottom:12px">CONTACT US — HOUSTON'S HOME SERVICES TEAM</h1><p style="color:#aaa;font-size:15px;max-width:520px">A licensed professional picks up every call. If it's an emergency, call us directly.</p></div></div>
<section class="section warm"><div class="section-inner"><div style="display:grid;grid-template-columns:3fr 2fr;gap:48px"><div style="background:#fff;border-radius:20px;padding:40px;box-shadow:0 4px 24px rgba(0,0,0,.08)"><h2 style="font-family:'Oswald',sans-serif;font-weight:600;text-transform:uppercase;letter-spacing:.05em;color:var(--navy);font-size:22px;margin-bottom:28px">Send Us a Message</h2><form action="<?php echo e(route('contact.submit')); ?>" method="POST" enctype="multipart/form-data" class="form-fields"><div class="field-row"><div class="field"><label style="color:#888">Full Name *</label><input type="text" name="name" placeholder="Jane Smith" style="background:#f5f5f5;border-color:#e5e5e5;color:#1A1A2E" required/></div><div class="field"><label style="color:#888">Phone *</label><input type="tel" name="phone" placeholder="(713) 555-1234" style="background:#f5f5f5;border-color:#e5e5e5;color:#1A1A2E" required/></div></div><div class="field"><label style="color:#888">Email *</label><input type="email" name="email" placeholder="jane@example.com" style="background:#f5f5f5;border-color:#e5e5e5;color:#1A1A2E" required/></div><div class="field"><label style="color:#888">Message *</label><textarea name="message" rows="5" placeholder="How can we help you?" style="background:#f5f5f5;border-color:#e5e5e5;color:#1A1A2E" required></textarea></div>
      <div class="field">
        <label style="color:#888">Photos of the Issue <span style="color:#666;font-weight:400;text-transform:none;letter-spacing:0;font-size:10px">(Optional — photos & videos help us prepare)</span></label>
        <div class="upload-zone" onclick="this.querySelector('input').click()">
          <input type="file" name="photos[]" accept="image/*,video/*" multiple style="display:none" onchange="handleUpload(event,this)"/>
          <div class="upload-idle">
            <div style="display:flex;gap:12px;justify-content:center;margin:0 auto 12px">
              <div class="upload-icon-wrap" style="margin:0">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="rgba(232,98,42,.7)" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
              </div>
              <div class="upload-icon-wrap" style="margin:0">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="rgba(232,98,42,.7)" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><polygon points="23 7 16 12 23 17 23 7"/><rect x="1" y="5" width="15" height="14" rx="2"/></svg>
              </div>
            </div>
            <p style="font-family:'Oswald',sans-serif;font-weight:600;text-transform:uppercase;letter-spacing:.06em;color:#ccc;font-size:13px;margin-bottom:4px">Click to upload photos or videos</p>
            <p style="color:#555;font-size:12px">Photos (JPG, PNG, HEIC) or Videos (MP4, MOV) · Up to 5 files · Max 50MB each</p>
          </div>
          <div class="upload-previews" style="display:none"></div>
        </div>
      </div>
      <?php echo csrf_field(); ?>
      <button type="submit" class="submit-btn" style="background:var(--orange);color:#fff;font-family:'Oswald',sans-serif;font-weight:700;font-size:18px;letter-spacing:.08em;text-transform:uppercase;padding:22px 32px;border-radius:8px;border:none;cursor:pointer;box-shadow:0 8px 32px rgba(232,98,42,.4);transition:all .2s;display:flex;align-items:center;justify-content:center;gap:12px;min-height:64px;width:100%">Send Message <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg></button></form></div><div style="display:flex;flex-direction:column;gap:16px"><div style="background:#C0392B;border-radius:14px;padding:24px"><p style="font-family:'Oswald',sans-serif;font-weight:700;text-transform:uppercase;color:#fff;font-size:15px;margin-bottom:8px">⚠ Emergency? Call Now</p><a href="tel:7130000000" style="font-family:'Oswald',sans-serif;font-weight:700;color:#fff;font-size:28px;text-decoration:none;display:block">(713) 000-0000</a><p style="color:rgba(255,255,255,.7);font-size:13px;margin-top:6px">We answer 24/7 — including 3AM</p></div><div style="background:#fff;border-radius:14px;padding:24px;box-shadow:0 2px 12px rgba(0,0,0,.06);display:flex;flex-direction:column;gap:14px"><div><p style="font-family:'Oswald',sans-serif;font-size:10px;letter-spacing:.1em;text-transform:uppercase;color:#aaa;margin-bottom:3px">Phone</p><a href="tel:7130000000" style="font-weight:600;color:var(--navy);text-decoration:none;font-size:16px">(713) 000-0000</a><p style="color:#aaa;font-size:12px;margin-top:2px">24/7 Emergency Line</p></div><div><p style="font-family:'Oswald',sans-serif;font-size:10px;letter-spacing:.1em;text-transform:uppercase;color:#aaa;margin-bottom:3px">Email</p><a href="mailto:info@lonestarhomeservices.com" style="color:var(--navy);text-decoration:none;font-size:13px">info@lonestarhomeservices.com</a></div><div style="border-top:1px solid #f0f0f0;padding-top:14px"><p style="font-family:'Oswald',sans-serif;font-size:10px;letter-spacing:.1em;text-transform:uppercase;color:#aaa;margin-bottom:8px">Hours</p><p style="font-size:14px;color:var(--charcoal)">Mon–Sat: 7AM–7PM</p><p style="font-size:14px;color:#C0392B;font-weight:600">Emergency: 24/7</p></div></div></div></div></div></section>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH /home/ahmad/Downloads/new lone star/lone_star/resources/views/pages/contact.blade.php ENDPATH**/ ?>