<?php $__env->startSection('title', 'Licensed Electrician in Texas — Panel Upgrades, EV Chargers, 24/7 Emergency'); ?>

<?php $__env->startSection('content'); ?>
<section class="service-hero">
  <div class="service-hero-bg"><img data-img="ELEC" src="" alt="Licensed electrician panel upgrade Texas"/><div class="service-hero-overlay"></div></div>
  <div class="service-hero-content"><div style="max-width:660px">
    <div class="service-badge"><span class="pulse"></span>Licensed & Insured · Texas</div>
    <h1 class="sh1">LICENSED ELECTRICIAN IN TEXAS</h1>
    <p class="sh1-sub">Panel upgrades · Rewiring · EV Chargers · Emergency Electrical · 24/7</p>
    <p class="sh1-body">From panel upgrades to emergency troubleshooting, we handle electrical work the right way: code-compliant, clean installs, and clear pricing. When Texas needs us, we’re ready.</p>
    <div class="sh1-ctas"><a href="<?php echo e(route('quote')); ?>" class="btn-hero-orange">Get a Free Electrical Quote <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg></a><a href="tel:7130000000" class="btn-hero-green">📞 (713) 000-0000</a></div>
  </div></div>
</section>
<section class="section warm"><div class="section-inner">
  <div class="section-head"><div class="accent-line"></div><h2 class="sh">EVERYTHING ELECTRICAL — DONE RIGHT</h2></div>
  <div class="service-items-grid">
    <div class="si-card"><div class="si-icon"><svg viewBox="0 0 24 24"><rect x="2" y="2" width="20" height="20" rx="2"/><line x1="8" y1="12" x2="16" y2="12"/><line x1="12" y1="8" x2="12" y2="16"/></svg></div><div class="si-title">Panel Upgrades & Replacements</div><p class="si-desc">Upgrades from 100A to 200A or 400A. Required for EV chargers, large AC units, hot tubs. We pull permits, pass inspections, stay code-compliant.</p></div>
    <div class="si-card"><div class="si-icon"><svg viewBox="0 0 24 24"><path d="M8 6h8M8 12h8M8 18h8"/></svg></div><div class="si-title">Full Home Rewiring</div><p class="si-desc">Older homes with aluminum wiring or cloth-jacketed wire are a fire risk. We rewire safely, minimize wall damage, and pull permits.</p></div>
    <div class="si-card"><div class="si-icon"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg></div><div class="si-title">Outlets & Switches</div><p class="si-desc">GFCI outlets for bathrooms, kitchens, garages. USB-C outlets. Smart switch installation for Alexa/Google/HomeKit.</p></div>
    <div class="si-card"><div class="si-icon"><svg viewBox="0 0 24 24"><line x1="12" y1="1" x2="12" y2="3"/><path d="M15.5 6.5a3.5 3.5 0 1 1-7 0"/><line x1="9.5" y1="10" x2="14.5" y2="10"/></svg></div><div class="si-title">Ceiling Fan Installation</div><p class="si-desc">Proper junction box installation, wiring for fan+light kits, dimmer compatibility. No wobble, no hum, done right.</p></div>
    <div class="si-card"><div class="si-icon"><svg viewBox="0 0 24 24"><rect x="1" y="6" width="12" height="12" rx="2"/><path d="M17 7l5 5-5 5M13 12h9"/></svg></div><div class="si-title">EV Charger Installation</div><p class="si-desc">Level 2 (240V) charger install for Tesla, Ford, Chevy, Rivian, and all EVs. Permit pulled, dedicated circuit run. Most installs completed in one day.</p></div>
    <div class="si-card"><div class="si-icon"><svg viewBox="0 0 24 24"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg></div><div class="si-title">Generator Hookup</div><p class="si-desc">Whole-home standby generator transfer switch installation. Hurricane season is the wrong time to find out you're not wired for backup power.</p></div>
    <div class="si-card"><div class="si-icon"><svg viewBox="0 0 24 24"><path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"/><rect x="8" y="2" width="8" height="4" rx="1"/></svg></div><div class="si-title">Electrical Safety Inspections</div><p class="si-desc">Full home electrical inspection. We check panel, wiring, grounding, GFCI protection. Written report included. Ideal for homebuyers and sellers.</p></div>
    <div class="si-card emergency"><div class="emergency-badge">24/7</div><div class="si-icon red-icon"><svg viewBox="0 0 24 24"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg></div><div class="si-title" style="color:#C0392B">24/7 Emergency Electrical</div><p class="si-desc">Sparks, burning smell, no power? We answer every call. Licensed Master Electrician on call. Fast emergency response.</p></div>
  </div>
</div></section>
<div class="faq-section"><div class="faq-inner">
  <div class="section-head"><div class="accent-line"></div><h2 class="sh">ELECTRICAL FAQ</h2></div>
  <div class="faq-list">
    <div class="faq-item open"><div class="faq-q"><div class="faq-q-content"><span class="faq-num">01</span><span class="faq-text">How much does a panel upgrade cost in Texas?</span></div><div class="faq-toggle"><svg viewBox="0 0 24 24"><polyline points="6 9 12 15 18 9"/></svg></div></div><div class="faq-a"><div class="faq-a-inner"><p>Most 200-amp panel upgrades cost between $1,200 and $2,500 depending on the panel brand, your current wiring condition, and whether we need to update your meter base. We provide a written, itemized quote before starting any work. We pull the permit and schedule the inspection — you don't need to do anything.</p></div></div></div>
    <div class="faq-item"><div class="faq-q"><div class="faq-q-content"><span class="faq-num">02</span><span class="faq-text">Do you need a permit to upgrade an electrical panel?</span></div><div class="faq-toggle"><svg viewBox="0 0 24 24"><polyline points="6 9 12 15 18 9"/></svg></div></div><div class="faq-a"><div class="faq-a-inner"><p>Yes — always. Any panel replacement or upgrade requires a permit through your local municipality. We handle permit applications, inspections, and final sign-off as part of every panel job.</p></div></div></div>
    <div class="faq-item"><div class="faq-q"><div class="faq-q-content"><span class="faq-num">03</span><span class="faq-text">Can you install a Level 2 EV charger at my home?</span></div><div class="faq-toggle"><svg viewBox="0 0 24 24"><polyline points="6 9 12 15 18 9"/></svg></div></div><div class="faq-a"><div class="faq-a-inner"><p>Yes. We install Level 2 (240-volt) chargers for all vehicle brands. Most EV charger installations take one day. We run a dedicated circuit, mount the charger, and pull the permit. Pricing starts around $499 for a straightforward garage install.</p></div></div></div>
    <div class="faq-item"><div class="faq-q"><div class="faq-q-content"><span class="faq-num">04</span><span class="faq-text">Do you offer 24/7 emergency electrical service?</span></div><div class="faq-toggle"><svg viewBox="0 0 24 24"><polyline points="6 9 12 15 18 9"/></svg></div></div><div class="faq-a"><div class="faq-a-inner"><p>Yes. We have a Licensed Master Electrician on call every night of the week, including weekends and holidays. If you have sparks, a burning smell, no power to critical circuits, or a panel issue that feels unsafe — call (713) 000-0000 immediately. We answer every call.</p></div></div></div>
  </div>
  <div class="faq-bottom"><div class="faq-bottom-text"><h3>Still have questions?</h3><p>We answer every call — including evenings and weekends.</p></div><a href="tel:7130000000" class="btn-green">📞 Call (713) 000-0000</a></div>
</div></div>
<?php echo $__env->make('pages.partials.quote-form', ['serviceType' => 'Electrical'], \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH /home/ahmad/Downloads/new lone star/lone_star/resources/views/pages/electrical.blade.php ENDPATH**/ ?>