<?php $__env->startSection('title', 'About Us — Lone Star Solutions Texas'); ?>

<?php $__env->startSection('content'); ?>
<div style="padding:100px 24px 80px;position:relative;overflow:hidden;background:var(--dark-navy)">
  <div style="position:absolute;inset:0;z-index:0"><img data-img="TEAM" src="" alt="Lone Star Texas Services Team" style="width:100%;height:100%;object-fit:cover;object-position:center top;opacity:.35"/></div>
  <div style="position:absolute;inset:0;background:linear-gradient(to right,rgba(7,26,48,.97),rgba(7,26,48,.82),rgba(7,26,48,.55));z-index:1"></div>
  <div style="position:absolute;inset:0;background:linear-gradient(to top,rgba(7,26,48,.7),transparent 60%);z-index:1"></div>
  <div style="max-width:1280px;margin:0 auto;position:relative;z-index:2">
    <div style="max-width:680px">
      <div style="display:inline-flex;align-items:center;gap:8px;background:rgba(232,98,42,.12);border:1px solid rgba(232,98,42,.3);color:var(--orange);font-family:'Oswald',sans-serif;font-size:11px;letter-spacing:.15em;text-transform:uppercase;padding:8px 18px;border-radius:99px;margin-bottom:28px">
        <span style="width:6px;height:6px;border-radius:50%;background:var(--orange);display:inline-block"></span>
        Texas · Since 2009
      </div>
      <div style="height:4px;width:48px;background:var(--orange);border-radius:2px;margin-bottom:24px"></div>
      <h1 style="font-family:'Oswald',sans-serif;font-weight:700;text-transform:uppercase;letter-spacing:.04em;color:#fff;font-size:clamp(36px,5vw,62px);line-height:1.05;margin-bottom:20px">TEXAS<br>SERVICES TEAM</h1>
      <p style="font-family:'Oswald',sans-serif;color:var(--orange);font-size:15px;letter-spacing:.12em;text-transform:uppercase;margin-bottom:20px">Who We Are & Why It Matters</p>
      <p style="color:#b0bec5;font-size:17px;line-height:1.7;max-width:560px">15+ years. 500+ jobs. One rule: treat every Texas customer the way you'd treat a neighbor — with honest pricing, licensed work, and real accountability.</p>
    </div>
  </div>
</div>
<section class="section" style="background:#fff"><div class="section-inner"><div style="display:grid;grid-template-columns:1.2fr 1fr;gap:64px;align-items:start"><div><div class="accent-line left"></div><h2 class="sh" style="margin-bottom:24px">OUR STORY</h2><p style="font-size:16px;line-height:1.75;color:rgba(26,26,46,.8);margin-bottom:18px">Lone Star Solutions was founded by licensed pros who watched too many homeowners get taken advantage of after major storms. Permit-free work that voided insurance. Quotes that doubled after the job started.</p><p style="font-size:16px;line-height:1.75;color:rgba(26,26,46,.8);margin-bottom:18px">We built this company on one belief: every Texas homeowner deserves a licensed professional who shows up on time, explains the problem clearly, gives an honest price, and does the work right the first time.</p><p style="font-size:16px;line-height:1.75;color:rgba(26,26,46,.8);margin-bottom:28px">Fifteen years later, we've expanded to electrical, plumbing, and roofing — three essential services, one trusted team. When your home or facility needs help, you call one number. We handle the rest.</p><div style="display:flex;gap:14px;flex-wrap:wrap"><a href="<?php echo e(route('quote')); ?>" class="btn-orange">Get a Free Quote</a><a href="tel:7130000000" class="btn-green">📞 (713) 000-0000</a></div></div><div class="stats-grid"><div class="stat-box"><div class="stat-val">500+</div><div class="stat-label">Jobs Completed</div><div class="stat-sub">Across Texas</div></div><div class="stat-box"><div class="stat-val">15+</div><div class="stat-label">Years in Business</div><div class="stat-sub">Built for Texas</div></div><div class="stat-box"><div class="stat-val">4.9★</div><div class="stat-label">Google Rating</div><div class="stat-sub">500+ reviews</div></div><div class="stat-box"><div class="stat-val">Statewide</div><div class="stat-label">Service Area</div><div class="stat-sub">Whole Texas coverage</div></div></div></div></div></section>
<section style="background:#fff;padding:0 24px 80px">
  <div style="max-width:1280px;margin:0 auto">
    <div style="border-radius:20px;overflow:hidden;position:relative;background:var(--navy);min-height:420px;display:flex;align-items:center;justify-content:center;box-shadow:0 16px 60px rgba(0,0,0,.15)">
      <div style="position:absolute;inset:0;background:linear-gradient(135deg,var(--dark-navy) 0%,var(--navy) 50%,#0d2e5a 100%)"></div>
      <div style="position:absolute;inset:0;background-image:repeating-linear-gradient(0deg,transparent,transparent 40px,rgba(255,255,255,.02) 40px,rgba(255,255,255,.02) 41px),repeating-linear-gradient(90deg,transparent,transparent 40px,rgba(255,255,255,.02) 40px,rgba(255,255,255,.02) 41px)"></div>
      <div style="position:relative;z-index:1;text-align:center;padding:48px">
        <div style="width:80px;height:80px;border-radius:50%;background:rgba(232,98,42,.15);border:2px dashed rgba(232,98,42,.4);display:flex;align-items:center;justify-content:center;margin:0 auto 20px">
          <svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="#E8622A" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        </div>
        <p style="font-family:'Oswald',sans-serif;font-weight:600;text-transform:uppercase;letter-spacing:.1em;color:#fff;font-size:18px;margin-bottom:8px">YOUR TEAM PHOTO HERE</p>
        <p style="color:#6b7a8d;font-size:14px;max-width:320px;margin:0 auto 24px;line-height:1.6">Add a photo of your crew, your truck fleet, or your team in action — drop it into the <code style="background:rgba(255,255,255,.08);padding:2px 8px;border-radius:4px;color:#E8622A">public/images/</code> folder and update the image path here.</p>
      </div>
      <div style="position:absolute;top:20px;left:24px;background:var(--orange);color:#fff;font-family:'Oswald',sans-serif;font-size:11px;letter-spacing:.1em;text-transform:uppercase;padding:6px 14px;border-radius:99px">The Lone Star Team · Texas</div>
      <div style="position:absolute;bottom:20px;right:24px;background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.12);color:#aaa;font-size:12px;padding:6px 14px;border-radius:99px;font-family:'Oswald',sans-serif;letter-spacing:.06em;text-transform:uppercase">15+ Years · 500+ Jobs</div>
    </div>
  </div>
</section>
<section class="section warm"><div class="section-inner"><div class="section-head"><div class="accent-line"></div><h2 class="sh">WHAT WE STAND FOR</h2></div><div class="values-grid"><div class="val-card"><div class="val-icon-wrap"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg></div><div class="val-title">Transparency</div><p class="val-body">Upfront pricing before we start. Itemized quotes. No upsells, no surprises. Every estimate is written and honored.</p></div><div class="val-card"><div class="val-icon-wrap"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8" r="6"/><path d="M15.477 12.89L17 22l-5-3-5 3 1.523-9.11"/></svg></div><div class="val-title">Quality</div><p class="val-body">Licensed professionals on every job. We pull permits. We pass inspections. We do it right the first time.</p></div><div class="val-card"><div class="val-icon-wrap"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg></div><div class="val-title">Community</div><p class="val-body">Texas-born and Texas-invested. When we say we're your neighbors, we mean it — and we show up with real accountability.</p></div></div></div></section>
<section style="background:var(--navy);padding:60px 24px"><div style="max-width:1280px;margin:0 auto"><div class="section-head" style="margin-bottom:32px"><div class="accent-line"></div><h2 class="sh light">OUR CREDENTIALS</h2></div><div class="creds-grid"><div class="cred-item"><div class="cred-dot"></div><p class="cred-text">Licensed Master Electrician — Texas TDLR</p></div><div class="cred-item"><div class="cred-dot"></div><p class="cred-text">Licensed Plumber — Texas State Board</p></div><div class="cred-item"><div class="cred-dot"></div><p class="cred-text">Licensed Roofing Contractor — Texas</p></div><div class="cred-item"><div class="cred-dot"></div><p class="cred-text">General Liability Insurance</p></div><div class="cred-item"><div class="cred-dot"></div><p class="cred-text">Workers' Compensation Coverage</p></div><div class="cred-item"><div class="cred-dot"></div><p class="cred-text">Bonded — All Technicians</p></div><div class="cred-item"><div class="cred-dot"></div><p class="cred-text">15+ Years in Business</p></div><div class="cred-item"><div class="cred-dot"></div><p class="cred-text">BBB Accredited Business</p></div></div></div></section>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH /home/ahmad/Downloads/new lone star/lone_star/resources/views/pages/about.blade.php ENDPATH**/ ?>